title: Chui Zeng
logo: /images/logo.png
description: > # your text below (remove <br> elements if you don't need line breaks)
 <br>
   A research data scientist with 10+ years’ Research & Development experience in environment, climate change, and ecosystem studies.
 <br>
   <a href="https://www.linkedin.com/in/chzeng">LinkedIn Profile</a> 
 <br>
   <a href="https://www.spatialblog.com">Personal Blog</a> 
 <br>
show_downloads: false
google_analytics: 
theme: jekyll-theme-minimal
