title: Chui Zeng
logo: /assets/img/logo.png
description: > # your text below (remove <br> elements if you don't need line breaks)
 <br>
   A research data scientist with 10+ years’ Research & Development experience in environment, climate change, and sustainability studies.
   A problem solver with profound understanding in geospatial data collection, processing, modelling, and analysis to support government policies and management.
 <br>
 <br>
   <a href="https://www.linkedin.com/in/chzeng">LinkedIn Profile</a> 
 <br>
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
