title: Chui Zeng
logo: /images/logo.png
description: > # your text below (remove <br> elements if you don't need line breaks)
 <br>
   As a research data scientist, I possess extensive research and development experiences in the fields of image processing, computer vision, climate change, and environmental studies
 <br>
   <a href="https://www.linkedin.com/in/chzeng">LinkedIn Profile</a> 
 <br>
   <a href="https://www.spatialblog.com">Personal Blog</a> 
 <br>
 <a href="mailto:chqzeng@gmail.com">Contact Me</a>
show_downloads: false
google_analytics: 
theme: jekyll-theme-minimal
#markdown: kramdown
